egami/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('img.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

img/urls.py
from django.conf.urls import url
from . import views

app_name = 'img'
urlpatterns = [

		url(r'^$', views.index, name = 'index'),
		url(r'^new$', views.new, name='new'),
		url(r'^(?P<pk>[\w-]+)/$', views.detail, name='detail'),
  ]

img/models.py
from django.db import models


class ImageClient(models.Model):
    image = models.ImageField(null=False, blank=False)

img/forms.py
from django import forms
from .models import ImageClient

class ImageForm(forms.ModelForm):
	class Meta:
		model = ImageClient
		fields =('image',)

img/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ImageForm
from .models import ImageClient
from PIL import Image, ImageOps
import stripe

# Create your views here.
def index(request):
    return render(request, 'img/index.html')

def new(request):
    """
    Returns mirror image from client.
    """
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = Image.open(form.cleaned_data['image'])
            img = ImageOps.mirror(image)
            #image = image.save(request.FILES['image'], 'jpeg')
            form_image = ImageClient(image=img)
            form_image.save()
            return redirect('img:detail', pk=form_image.id)
    else:
        form = ImageForm()
    return render(request, 'img/new_egami.html', {'form':form})


def detail(request, pk):
    image = get_object_or_404(ImageClient, pk=pk)
    return render(request, 'img/egami_detail.html', {'image':image})

img/templates/img/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"  crossorigin="anonymous">
    <title>Egami - Nettoyez vos images</title>
</head>
<body>

    <div class='container'>
      {% block content %}
      {% endblock %}
      </div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"  crossorigin="anonymous"></script>


</body>
</html>

img/templates/img/egami_detail.html
{% extends 'img/base.html' %}
{% load static %}
{% load staticfiles %}
{% block content %}

<div class="row">

    <div class="col-md-4"></div>
    <div class="col-md-4">
        <p> Telechargez votre image:</p> <br>
        <img src="{{ image.image.url }}" class ='img-responsive'>
    </div>
    <div class="col-md-4"></div>



</div>

{% endblock %}

img/templates/img/index.html
{% extends 'img/base.html' %}

{% block content %}

<div class="row">

    <div class="col-md-4"></div>
    <div class="col-md-4">
        <p>Pour nettoyer votre image <br>
        <a href="{% url 'img:new' %}" class="btn btn-default"> Cliquez ici</a></p>
    </div>
    <div class="col-md-4"></div>



</div>

{% endblock %}

img/templates/img/new_egami.html
{% extends 'img/base.html' %}

{% block content %}

<div class="row">

    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
    <div class="col-md-4"></div>



</div>

{% endblock %}